CREATE TABLE YEAR_MST
(
  YEAR_ID             NUMBER,
  NUMBER_PERIOD       NUMBER(10)                NOT NULL,
  FROM_MNTH           NUMBER(10),
  FROM_YEAR           NUMBER(10),
  TO_MNTH             NUMBER(10),
  TO_YEAR             NUMBER(10),
  OPEN_NEW_YEAR       NUMBER,
  CLOSE_YEAR          NUMBER,
  CLOSE_YEAR_USER_NO  NUMBER,
  CLOSE_YEAR_DATE     DATE,
  EDITUSER            VARCHAR2(50 BYTE),
  EDITDATE            DATE,
  ADDUSER             VARCHAR2(50 BYTE),
  ADDDATE             DATE,
  EDITDEVICE          VARCHAR2(50 BYTE),
  ADDDEVICE           VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMPANY
(
  COM_ID        NUMBER,
  COM_L_NAME    VARCHAR2(50 BYTE)               NOT NULL,
  COM_F_NAME    VARCHAR2(50 BYTE),
  COM_DESC      VARCHAR2(50 BYTE),
  COM_WEB_SITE  VARCHAR2(50 BYTE),
  COM_EMAIL     VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE YEAR_DTL
(
  YEAR_ID     NUMBER,
  PRIOD_ID    NUMBER(8),
  MNTH_ORDER  NUMBER(10)                        NOT NULL,
  PRD_L_NAME  VARCHAR2(40 BYTE),
  PRD_F_NAME  VARCHAR2(40 BYTE),
  FROM_DATE   DATE,
  T_DATE      DATE,
  YEARS       NUMBER(10),
  MNTH_STOP   NUMBER,
  MNTH_CLS    NUMBER,
  EDITUSER    VARCHAR2(50 BYTE),
  EDITDATE    DATE,
  ADDUSER     VARCHAR2(50 BYTE),
  ADDDATE     DATE,
  EDITDEVICE  VARCHAR2(50 BYTE),
  ADDDEVICE   VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE BRANCH
(
  BR_SER      NUMBER,
  BR_ID       NUMBER                            NOT NULL,
  COM_L_NAME  VARCHAR2(50 BYTE),
  COM_F_NAME  VARCHAR2(50 BYTE),
  BR_L_NAME   VARCHAR2(50 BYTE),
  BR_F_NAME   VARCHAR2(50 BYTE),
  BR_IMG      VARCHAR2(40 BYTE),
  BR_L_ADRS   VARCHAR2(50 BYTE),
  BR_F_ADRS   VARCHAR2(50 BYTE),
  BR_L_PHONE  VARCHAR2(40 BYTE),
  BR_F_PHONE  VARCHAR2(40 BYTE),
  BR_L_FAX    VARCHAR2(40 BYTE),
  BR_F_FAX    VARCHAR2(40 BYTE),
  BR_L_DESC   VARCHAR2(50 BYTE),
  BR_F_DESC   VARCHAR2(50 BYTE),
  BR_YEAR     NUMBER(10),
  COM_ID      NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE YEAR_MST ADD (
  CONSTRAINT YEAR_MST_PK
 PRIMARY KEY
 (YEAR_ID));


ALTER TABLE COMPANY ADD (
  CONSTRAINT COMPANY_PK
 PRIMARY KEY
 (COM_ID));


ALTER TABLE BRANCH ADD (
  CONSTRAINT BRANCH_PK
 PRIMARY KEY
 (BR_SER));


ALTER TABLE YEAR_DTL ADD (
  CONSTRAINT YEAR_ID_FK 
 FOREIGN KEY (YEAR_ID) 
 REFERENCES YEAR_MST (YEAR_ID));


ALTER TABLE BRANCH ADD (
  CONSTRAINT COP_ID_FK 
 FOREIGN KEY (COM_ID) 
 REFERENCES COMPANY (COM_ID));




